FROM node:16 as builder

COPY . /app
WORKDIR /app

RUN yarn install
RUN yarn build 

## ===========================

FROM library/nginx:1.19
COPY --from=builder /app/build /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]